version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
